{"question": "\nI ran my qsvm code on the quantum computer and I'm facing the following error:\nFAILURE: Can not get job id, Resubmit the qobj to get job id. Terra job error: \"Error submitting job: '400 Client Error: Bad Request for url: https://api.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/Jobs. Reached maximum number (5) of concurrent jobs, **Error code: 3458.**'\" \nJob limit reached, waiting for job 5ef1bc3ecd20b1001387fa06 to finish before submitting the next one.\nFAILURE: Job id: 5ef1bc4edab6ee0013416233 is cancelled. Re-submit the Qobj.\nFAILURE: Job id: 5ef1bc546daf510014814cd8 is cancelled. Re-submit the Qobj.\nFAILURE: Job id: 5ef1bc5a13b5f900139e97c5 is cancelled. Re-submit the Qobj.\nFAILURE: Job id: 5ef1bc62c7453600138726d0 is cancelled. Re-submit the Qobj.\n\nThe last line is repeating every few minutes. The url does not exist. I did run my code on the simulator and it worked.\nIt uses 5 features and hence 5 qubits. Could anyone please help me out?\nThe code:\ndata = np.genfromtxt('diabetes.csv', delimiter=',', names=True, case_sensitive=True)\ndata = np.array(data.tolist()) # was an array of arrays earlier\ndata = np.delete(data, 7, axis = 1)\ndata = np.delete(data, 3, axis = 1)\ndata = np.delete(data, 2, axis = 1)\nprint(data.shape)\nx = np.copy(data[:,0:5]) #features\ny = np.copy(data[:,5]) #targets\nfeatures = 5\nfrom sklearn.model_selection import train_test_split\nimport qiskit\nfrom qiskit import BasicAer\nfrom qiskit.aqua import QuantumInstance\nfrom qiskit.aqua.algorithms import QSVM\n  \nfrom qiskit.aqua.components.multiclass_extensions import one_against_rest, all_pairs\nfrom qiskit.aqua.components.feature_maps import SecondOrderExpansion\nprovider = qiskit.IBMQ.load_account()\nbackend = provider.get_backend('ibmq_16_melbourne')\ntrain_x, test_x, train_y, test_y = train_test_split(x[0:101], y[0:101], test_size=0.2)\n\ntraining_data = {'A':train_x[train_y==0],'B':train_x[train_y==1]}\ntesting_data = {'A':test_x[test_y==0],'B':test_x[test_y==1]}\nfeature_map = SecondOrderExpansion(feature_dimension=features,depth=2,entanglement='full')\nsvm = QSVM(feature_map,training_data,testing_data)\nshots = 1 \nquantum_instance = QuantumInstance(backend,shots=shots,skip_qobj_validation=False)\n%%time\nresult = svm.run(quantum_instance) \n\n", "answers": ["\ntldr: this is caused by a change in behavior of the IQX server that needs to be fixed.\nAqua may submit multiple jobs for an experiment under the cover. However, with a public account, you can only have 5 jobs running in parallel at the same time. That's what caused the first error:\nFAILURE: Can not get job id, Resubmit the qobj to get job id. Terra job error: \"Error submitting job: '400 Client Error: Bad Request for url: https://api.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/Jobs. Reached maximum number (5) of concurrent jobs, **Error code: 3458.**'\" \n\nAqua then tried to wait for the oldest job to finish before submitting the next one, as indicated by this message:\nJob limit reached, waiting for job 5ef1bc3ecd20b1001387fa06 to finish before submitting the next one.\n\nInstead of waiting indefinitely for the oldest, the code retries the submit every 5 minutes, in case a spot frees up for some reason. It looks like there is a behavior change so that instead of getting another 3458 error, the retried submit went through but the job was immediately cancelled, giving the rest of the error messages. Without the 3458 error, Aqua just kept re-submitting the jobs which kept getting cancelled.\n"], "comments": [], "link": "https://quantumcomputing.stackexchange.com//questions/12619/error-code-3458?r=SearchResults"}