{"question": "\nI am using Jupyter notebook to write and running my qiskit codes (python 3.6)\nand every time I encounter the message: LookupError: backend \"ibmqx4\" is not found, right now the ibmqx4 computer is not in maintenance and it running well.\nI tried to regenerate Apitoken in the advanced option and make correspondingly the file Qconfig.py but the message still appears.\nlook at the example for a code that I write:\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport qiskit as qk\nfrom qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute, register\n\n\nimport Qconfig\n\n\n\n    batch = []\nn=50\nt=450\n// we defining n similar quantum circuits\nfor j in range(1,n+1):\n    q = QuantumRegister(1)\n    c = ClassicalRegister(1)\n    qc = QuantumCircuit(q, c)\n    qc.x(q)\n    qc.barrier()\n\n\n// we decide the pausing time of the system be t*Gate Time\n    for i in range(t):\n        qc.iden(q)\n    qc.measure(q,c)    \n   //we append every circuit we create to batch so batch is like a list of n \n  circuits\n    batch.append(qc)\n\n// we executing all the n circuits and for each we run 1024 shots\nshots = 1024\njob = execute(qc,'ibmqx4',shots=shots)\n\nand I get the output from the last row:\n---------------------------------------------------------------------------\nLookupError                               Traceback (most recent call last)\n<ipython-input-38-a89f2171589f> in <module>()\n      1 # we executing all the n circuits and for each we run 1024 shots\n      2 shots = 1024\n----> 3 job = execute(qc,'ibmqx4',shots=shots)\n\n~\\Anaconda3\\envs\\QISKit\\lib\\site-packages\\qiskit\\wrapper\\_wrapper.py in execute(circuits, backend, config, basis_gates, coupling_map, initial_layout, shots, max_credits, seed, qobj_id, hpc, skip_transpiler)\n    270     # pylint: disable=missing-param-doc, missing-type-doc\n    271     if isinstance(backend, str):\n--> 272         backend = _DEFAULT_PROVIDER.get_backend(backend)\n    273     qobj = compile(circuits, backend,\n    274                    config, basis_gates, coupling_map, initial_layout,\n\n~\\Anaconda3\\envs\\QISKit\\lib\\site-packages\\qiskit\\wrapper\\defaultqiskitprovider.py in get_backend(self, name)\n     29 \n     30     def get_backend(self, name):\n---> 31         name = self.resolve_backend_name(name)\n     32         for provider in self.providers:\n     33             try:\n\n~\\Anaconda3\\envs\\QISKit\\lib\\site-packages\\qiskit\\wrapper\\defaultqiskitprovider.py in resolve_backend_name(self, name)\n    218 \n    219         if resolved_name not in available:\n--> 220             raise LookupError('backend \"{}\" not found.'.format(name))\n    221 \n    222         return resolved_name\n\nLookupError: backend \"ibmqx4\" not found.\n\nplease help me to solve this repetitive bug...\n", "answers": ["\nI got it, there is need to add two codes :\nthe first one in the begining before starting programming:\nimport  sys,,  time,,  getpass\ntry:\n    sys.path.append(\"../../\") # go to parent dir\n    import Qconfig\n    qx_config = {\n        \"APItoken\": Qconfig.APItoken,\n        \"url\": Qconfig.config['url']}\n    print('Qconfig loaded from %s.' % Qconfig.__file__)\nexcept:\n    APItoken = getpass.getpass('Please input your token and hit enter: ')\n    qx_config = {\n        \"APItoken\": APItoken,\n        \"url\":\"https://quantumexperience.ng.bluemix.net/api\"}\n    print('Qconfig.py not found in qiskit-tutorial directory; Qconfig loaded using user input.')\n\nthe second one is before execution:\nregister(qx_config['APItoken'], qx_config['url'])\n\nhope I helped anyone with similar error!\n"], "comments": [], "link": "https://quantumcomputing.stackexchange.com//questions/4210/how-to-deal-with-lookuperror-backend-ibmqx4-is-not-found?r=SearchResults"}