{"0": {"author": "barthelemymp", "date": "1556707177946", "content": "Hello,\nI\u2019m doing the serie of tutorials, to learn a bit about PennyLane.\nSo far everything was working just fine, but then I tried the PyTorch tutorial, which start by using a forest devices. I installed the forest software and the plugin, however when I run :\nimport pennylane as qml\nimport torch\nfrom torch.autograd import Variable\ndev = qml.device('forest.qvm', device='2q', noisy=True)\n\nI get the following error:\n---------------------------------------------------------------------------\nAttributeError                            Traceback (most recent call last)\n<ipython-input-2-2cf089c8119a> in <module>\n----> 1 dev = qml.device('forest.qvm', device='2q', noisy=True)\n\n~\\.conda\\envs\\penny\\lib\\site-packages\\pennylane\\__init__.py in device(name, *args, **kwargs)\n    210 \n    211         # load plugin device\n--> 212         return plugin_device_class(*args, **options)\n    213 \n    214     raise DeviceError('Device does not exist. Make sure the required plugin is installed.')\n\n~\\.conda\\envs\\penny\\lib\\site-packages\\pennylane_forest\\qvm.py in __init__(self, device, shots, noisy, **kwargs)\n     91                              \"a valid QVM quantum computer, or a NetworkX graph object.\")\n     92 \n---> 93         super().__init__(num_wires, shots, **kwargs)\n     94 \n     95         # get the qc\n\n~\\.conda\\envs\\penny\\lib\\site-packages\\pennylane_forest\\device.py in __init__(self, wires, shots, **kwargs)\n    187     def __init__(self, wires, shots, **kwargs):\n    188         super().__init__(wires, shots)\n--> 189         self.forest_url = kwargs.get('forest_url', pyquil_config.compiler_url)\n    190         self.qvm_url = kwargs.get('qvm_url', pyquil_config.qvm_url)\n    191         self.compiler_url = kwargs.get('compiler_url', pyquil_config.compiler_url)\n\nAttributeError: 'PyquilConfig' object has no attribute 'compiler_url'\n\nI have to admit that I have no idea how to solve it, so any help would be welcome.\nAll the best,\nb\n\n\n Solved by barthelemymp in post #8 \n\n\n                little remark, what worked for was python setup.py and not pip install !\n              \n", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/1"}, "1": {"author": "nathan", "date": "1556719799190", "content": "Hi barthelemymp,\nThere are breaking changes in the latest versions of Rigetti software, and it affects PennyLane. I\u2019m not sure if this is the same issue (@josh knows this better \u2013 perhaps he can comment), but we are working with Rigetti to fix the plugin.\nGreetings,\nNathan", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/2"}, "2": {"author": "josh", "date": "1556757575989", "content": "Hi @barthelemymp, thank you for flagging this! I will take a look and see if I can reproduce the bug.\nCan I ask you to run the following three commands, to determine the versions of quilc, QVM, and PyQuil you are using:\nquilc --version\nqvm --version\npython -c \"import pyquil; print(pyquil.__version__)\"\n", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/3"}, "3": {"author": "barthelemymp", "date": "1556833726441", "content": "Hello Josh\nHere are the results from the code you asked:\nquilc --version\n1.6.0 [1d29de5]\nqvm --version\n1.6.0 [26b5bd8]\npython -c \"import pyquil; print(pyquil.__version__)\"\n2.7.0\nFor this one, It was on the conda environnement I created for penny lane. Maybe there is a problem related the conda environment? Penny lane and the forest plugin are only installed on the envs\u2026\nBest regards\nBarth\u00e9l\u00e9my", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/4"}, "4": {"author": "josh", "date": "1557123981100", "content": "Hi @barthelemymp,\nI was able to reproduce the error using the version of PennyLane-Forest installed via pip.\nThis bug is currently fixed in the latest GitHub master branch of PennyLane-Forest. I will update the pip version so this bug is fixed for users that pip install pennylane-forest ASAP, thank you for letting us know!\nIn the meantime, you can switch to the GitHub development version as follows:\ngit clone https://github.com/rigetti/pennylane-forest\ncd pennylane-forest && pip install -e .\n\nAfter running those above two commands, the tutorial linked above should work without error.2 Replies2", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/5"}, "5": {"author": "SreeramV181", "date": "1558548558589", "content": "Hey Josh.\nI have the same error. I tried doing what you did but it still isn\u2019t working for me.", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/6"}, "6": {"author": "josh", "date": "1558551954886", "content": "Hi @SreeramV181,\nCan I ask you to run the following three commands, to determine the versions of quilc, QVM, and PyQuil you are using:\nquilc --version\nqvm --version\npython -c \"import pyquil; print(pyquil.__version__)\"\n```Could you post the error message you are getting", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/7"}, "7": {"author": "barthelemymp", "date": "1560352090896", "content": "little remark, what worked for was python setup.py and not pip install !Solution", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/8"}, "8": {"author": "_risto", "date": "1624989502052", "content": "Hi @barthelemymp\nWhere did you write this?\nI am getting errors while trying to run\npip install pennylane-forest & pip install pyquil\nthus I can\u2019t run the tutorials because I get DeviceError: Device does not exist. Make sure the required plugin is installed.", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/9"}, "9": {"author": "theodor", "date": "1624995378769", "content": "Hi @_risto. What errors are you getting when attempting to install pennylane-forest and pyquil? If you could perhaps start a new thread on the forum and post the outputs there, I could attempt to help you figure out what\u2019s going wrong. ", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/10"}, "10": {"author": "_risto", "date": "1624996111447", "content": "Hi @theodor\nBoth times I get:\n\n\nimage1516\u00d7593 29.6 KB\n", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/11"}, "11": {"author": "antalszava", "date": "1625000482746", "content": "Hi @_risto,\nIt seems that the issue you\u2019re facing will be related to the immutables package as the wheels cannot be built for that one in particular.\nThis seems to be a problem related to installing PyQuil in specific, rather than PennyLane or the PennyLane-Forest plugin. Perhaps there\u2019s a lead in the complete traceback, on what might be going wrong. Locally I have immutables==0.6 and pyquil==2.21.0 installed, perhaps it is worth an attempt to try installing those versions in specific.", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/12"}, "12": {"author": "antalszava", "date": "1625008211958", "content": "Perhaps checking your gcc version (C++ compiler) could also help, it might be required by immutables.", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/13"}, "13": {"author": "_risto", "date": "1624996111447", "content": "Hi @theodor\nBoth times I get:\n\n\nimage1516\u00d7593 29.6 KB\n", "link": "https://discuss.pennylane.ai//t/problem-using-the-forest-plugin/123/14"}}