{"0": {"author": "Yang", "date": "1650513391942", "content": "Hi, I am employing VQE to solve the ground state of hydrogen molecule. However, when I try to estimate the expectation of Hamiltonian with finite shots, an error raises as \u201cValueError: Can only return the expectation of a single Hamiltonian observable\u201d. What is the possible cause of this issue? Please let me know if any additional implementation details are needed to analyse.", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/1"}, "1": {"author": "CatalinaAlbornoz", "date": "1650579349253", "content": "Hi @Yang, welcome to the forum!\nYes, we need to see your code in order to help you.\nSome things that you can check beforehand are:\n\nCheck that your Python version is at least 3.7 or higher\nCheck that you\u2019re using the latest PennyLane version (v0.22)\nCheck the return statements in some of our quantum chemistry demos. On the right hand side you will be able to download the notebook and run it locally. If you find an error here then the problem may not be in your code but in your environment. If the demos run well but your code doesn\u2019t then take a close look at what expectation values you\u2019re trying to retrieve. It may be that the specific device you\u2019re using causes problems too.\n\nIn any case do share with us your solution if you manage to fix your problem or your code in case that the items above don\u2019t solve it.\nI hope this helps though!", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/2"}, "2": {"author": "Yang", "date": "1650788991872", "content": "Thanks for your advice. Here is my code.\nimport pennylane as qml\nfrom pennylane import numpy as np\nimport torch\nimport math\n\nPauliGate = {\n    'X': qml.PauliX,\n    'Y': qml.PauliY,\n    'Z': qml.PauliZ,\n    'I': qml.Identity,\n}\n\ndef gen_h(hamiltonian):\n    coefs = []\n    obs = []\n    for h in hamiltonian:\n        coefs.append(hamiltonian[h])\n        ob = PauliGate[h[0]](0)\n        for i in range(1, len(h)):\n            ob = ob @ PauliGate[h[i]](i)\n        obs.append(ob)\n    return qml.Hamiltonian(coefs, obs, simplify=False, grouping_type='qwc')\n\ndef circuit_h2(param, A=None, p=0):\n    qml.PauliX(0)\n    qml.PauliX(1)\n    for i in [0, 1, 2, 3]:\n        qml.Rot(*param[i], wires=i)\n    qml.CNOT(wires=[2, 3])\n    qml.CNOT(wires=[2, 0])\n    qml.CNOT(wires=[3, 1])\n    if p > 0 and p < 1:\n        for j in range(4):\n            qml.DepolarizingChannel(p, wires=j)\n    return qml.expval(A)\n\nclass VQE_H2(torch.nn.Module):\n    def __init__(self, dev, n_qubits, hamiltonian, p=0, n_layers=2) -> None:\n        super().__init__()\n\n        self.param = torch.nn.Parameter(torch.FloatTensor(n_qubits, 3).uniform_(0, 2*math.pi))\n        self.register_parameter('param', self.param)\n\n        self.cir = qml.qnode(dev, interface='torch')(circuit_h2)\n        self.hamiltonian = gen_h(hamiltonian)\n        self.p = p\n\n    def forward(self):\n        return self.cir(self.param, A=self.hamiltonian, p=self.p)\n\nif __name__ == '__main__':\n    dev = qml.device(\"default.qubit\", wires=4, shots=1000)\n    h_part={'XXYY': -0.04221755692243391, 'XYYX': 0.04221755692243391, 'ZIIZ': 0.1768099603861226, 'YXXY': 0.04221755692243391}\n    model = VQE_H2(dev, 4, h_part, p=0)\n    loss = model()\n\nI find that when I use the whole Hamiltonian of hydrogen molecule as observable, the code works well. When I use part of Hamiltonian terms as observable, it reports the error.", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/3"}, "3": {"author": "CatalinaAlbornoz", "date": "1650922809415", "content": "Hi @Yang,\nThanks for sharing your code. It runs correctly for me. What is the line that you change that makes it stop working? Could you please share the non-working code too?", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/4"}, "4": {"author": "Yang", "date": "1650939852253", "content": "Hi @CatalinaAlbornoz,\nactually the code I share does not work for me. I run the code on the HPC in the Python environment with Python=3.7.7, PennyLane=0.22.2, Pytorch=1.10.1. It reports the ValueError.  However, when I run on my laptop with Python=3.8.10, PennyLane=0.22.2, Pytorch=1.10.2, it works correctly as you. This phenomenon makes me quite confused.", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/5"}, "5": {"author": "CatalinaAlbornoz", "date": "1651010585019", "content": "Hi @Yang, what operating system are you using on the HPC and on your laptop? I just ran the code on a Python 3.7 environment with no errors.\nYou may have a \u2018float64\u2019 vs \u2018float32\u2019 problem too.\nPlease let me know if this helps.", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/6"}, "6": {"author": "Yang", "date": "1651052311039", "content": "Hi @CatalinaAlbornoz, the system on HPC and my laptop is CentOS release 6.9 (Final) and  Windows 10.", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/7"}, "7": {"author": "CatalinaAlbornoz", "date": "1651088383886", "content": "This is very strange @Yang \nCould you please send me the full error traceback?\nAlso, did you try the option of setting the default dtype to float32 and float64 as explained in the pytorch docs?\nFinally, it could help if you could send me the output of import pennylane as qml; qml.about()", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/8"}, "8": {"author": "Yang", "date": "1651656149453", "content": "@CatalinaAlbornoz Yes, quite strange. I tried to set dtype to float64 in pytorch and the error still exists. Here are the full error information:\n/var/spool/PBS/mom_priv/jobs/6288971.pbsserver.SC: line 10: py37/bin/activate: No such file or directory\n Traceback (most recent call last):\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/_device.py\", line 703, in batch_transform\n     return qml.transforms.hamiltonian_expand(circuit, group=False)\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/transforms/hamiltonian_expand.py\", line 144, in hamiltonian_expand\n     for indices in hamiltonian.grouping_indices\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/transforms/hamiltonian_expand.py\", line 144, in <listcomp>\n     for indices in hamiltonian.grouping_indices\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/math/multi_dispatch.py\", line 178, in wrapper\n     return fn(*args, **kwargs)\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/math/multi_dispatch.py\", line 543, in stack\n     return np.stack(values, axis=axis, like=like)\n   File \"/home/xxx/py37/lib/python3.7/site-packages/autoray/autoray.py\", line 84, in do\n     return get_lib_fn(backend, fn)(*args, **kwargs)\n   File \"<__array_function__ internals>\", line 6, in stack\n   File \"/home/xxx/py37/lib/python3.7/site-packages/numpy/core/shape_base.py\", line 423, in stack\n     raise ValueError('need at least one array to stack')\n ValueError: need at least one array to stack\n\n The above exception was the direct cause of the following exception:\n\n Traceback (most recent call last):\n   File \"demo.py\", line 32, in <module>\n     loss = model()\n   File \"/home/xxx/py37/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 1102, in _call_impl\n     return forward_call(*input, **kwargs)\n   File \"/xxx/circuit/vqe_pl.py\", line 82, in forward\n     return self.cir(self.param, A=self.hamiltonian, p=self.p)\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/qnode.py\", line 585, in __call__\n     **self.execute_kwargs,\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/interfaces/batch/__init__.py\", line 314, in execute\n     tapes, batch_fn = qml.transforms.map_batch_transform(device.batch_transform, tapes)\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/transforms/batch_transform.py\", line 476, in map_batch_transform\n     new_tapes, fn = transform(t)\n   File \"/home/xxx/py37/lib/python3.7/site-packages/pennylane/_device.py\", line 708, in batch_transform\n     ) from e\n ValueError: Can only return the expectation of a single Hamiltonian observable\n\n\nAnd the following is the output of qml.about()\n Name: PennyLane\n Version: 0.22.2\n Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.\n Home-page: https://github.com/XanaduAI/pennylane\n Author:\n Author-email:\n License: Apache License 2.0\n Location: /home/yqia7342/py37/lib/python3.7/site-packages\n Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml\n Required-by: PennyLane-Lightning, PennyLane-qiskit\n Platform info:           Linux-2.6.32-696.16.1.el6.x86_64-x86_64-with-centos-6.9-Final\n Python version:          3.7.7\n Numpy version:           1.20.1\n Scipy version:           1.6.1\n Installed devices:\n - default.gaussian (PennyLane-0.22.2)\n - default.mixed (PennyLane-0.22.2)\n - default.qubit (PennyLane-0.22.2)\n - default.qubit.autograd (PennyLane-0.22.2)\n - default.qubit.jax (PennyLane-0.22.2)\n - default.qubit.tf (PennyLane-0.22.2)\n - default.qubit.torch (PennyLane-0.22.2)\n - qiskit.aer (PennyLane-qiskit-0.17.0)\n - qiskit.basicaer (PennyLane-qiskit-0.17.0)\n - qiskit.ibmq (PennyLane-qiskit-0.17.0)\n - lightning.qubit (PennyLane-Lightning-0.22.1)\n", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/9"}, "9": {"author": "CatalinaAlbornoz", "date": "1651775847375", "content": "Hi @Yang, I think the problem may be due to the way PyTorch is built in your HPC environment. I would recommend that you try with a new virtual environment. If that doesn\u2019t work maybe you can try a new virtual machine. If that doesn\u2019t work the problem may be with CentOS.\nPlease let me know if you manage to get it working there!", "link": "https://discuss.pennylane.ai//t/valueerror-can-only-return-the-expectation-of-a-single-hamiltonian-observable/1848/10"}}